sudo: false
dist: trusty
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install
  - polymer install --variants

script:
  # test against Polymer 2
  - gemini test test/visual
  - gemini test test/visual -c .gemini-ie.yml

  # test against Polymer 1
  - rm -rf bower_components
  - mv bower_components-1.x bower_components
  - gemini test test/visual
  - gemini test test/visual -c .gemini-ie.yml
